name: dataphilly-marl
channels:
    - anaconda
    - conda-forge
    - pytorch
dependencies:
    - python=3.9
    - pytorch=1.9.0
    - gym=0.19.0
    - ray-rllib=1.6
    - flake8
    - pytest
    - hypothesis
    - pytype
